Repository tigerbeetle-rust/tigerbeetle-unofficial, pull requests merged in 2024-12, with the labels that each got.

#26 Support new TigerBeetle functionality
  core/examples/c_port_low_level.rs
  core/src/lib.rs
  core/src/query_filter.rs
  examples/c_port_high_level.rs
  src/lib.rs
  src/reply.rs
  sys/build.rs
Labels: feature, k::api

#39 feat: add `id` method
  CHANGELOG.md
  Cargo.toml
  src/id.rs
  src/lib.rs
Labels: feature, k::api

#29 Refactor `error` module in `core` crate
  core/src/error.rs
  core/src/lib.rs
Labels: enhancement, k::refactor

#41 Remove MIT license
  CHANGELOG.md
  Cargo.toml
  LICENSE
  LICENSE.MIT
  README.md
  core/LICENSE
  core/LICENSE.APACHE
  core/LICENSE.MIT
  src/id.rs
  sys/LICENSE
  sys/LICENSE.APACHE
  sys/LICENSE.MIT
Labels: enhancement, k::license
